# Generated by Django 3.2.5 on 2021-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentapp', '0005_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertype',
            name='type_name',
            field=models.CharField(max_length=15),
        ),
    ]
