# Generated by Django 3.2.5 on 2021-09-11 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentapp', '0006_alter_usertype_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appointmentapp.usertype'),
        ),
    ]
